#!/usr/bin/env bash
# Regenerate qsb_carrier_sm89.h, the native sm_89 image that QsbCarrier.h loads.
# Adapted from Ryun1's pinning-track build_carrier.sh (public submission 25bd990a, GPL-3).
# Development tool, never run by the ranked harness. Rerun after ANY edit to device code
# in this tree (subset.cu, tests/gpu_epochs/tree.cu or a header they include).
#   NVCC=/path/to/cuda-12.8/bin/nvcc ./build_carrier.sh [QSB_ZEROS_N]
# Build the image with the ranked runner's toolkit, CUDA 12.8: a cubin from a newer
# toolkit may fail to load on the runner's driver, and the carrier then stays off.
# NVCC selects the compiler (default: nvcc on PATH); CUOBJDUMP the dump tool (default:
# cuobjdump next to NVCC, else on PATH; any version reads the cubin). Extra nvcc flags
# (e.g. OpenSSL include paths) can be passed in QSB_CARRIER_NVCC_FLAGS.
set -euo pipefail
cd "$(dirname "$0")"
Z=${1:-24}
NVCC=${NVCC:-nvcc}
if [ -z "${CUOBJDUMP:-}" ]; then
    CUOBJDUMP=cuobjdump
    d=$(dirname "$(command -v "$NVCC")")
    [ -x "$d/cuobjdump" ] && CUOBJDUMP="$d/cuobjdump"
fi
W=$(mktemp -d)   # logs and the raw cubin stay out of the submission directory
"$NVCC" --version | tail -n 2 | head -n 1 > "$W/nvcc.txt"
if ! grep -q "release 12\.8," "$W/nvcc.txt"; then
    echo "build_carrier: WARNING: $(cat "$W/nvcc.txt") is not CUDA 12.8 (the ranked runner's toolkit);" \
         "the image may not load there. Set NVCC to a 12.8 nvcc." >&2
fi
# shellcheck disable=SC2086
"$NVCC" -O3 -DQSB_ZEROS_N="$Z" -DQSB_CARRIER_BUILD=1 -arch=sm_89 -cubin ${QSB_CARRIER_NVCC_FLAGS:-} \
     -Xptxas -v -o "$W/c.cubin" subset.cu 2> "$W/ptxas.log"
"$CUOBJDUMP" -symbols "$W/c.cubin" > "$W/symbols.txt"
"$CUOBJDUMP" -sass "$W/c.cubin" > "$W/sass.txt"
python3 - "$Z" "$W" <<'PY'
import base64, glob, hashlib, re, sys
zeros = int(sys.argv[1]); W = sys.argv[2]
syms = open(W + "/symbols.txt").read()
want = [  # order must match enum QsbCarrierKernel in QsbCarrier.h
    ("QK_EG",  r"_Z19kernel_epoch_groups\w+"),
    ("QK_BEI", r"_Z23kernel_build_epochs_inc\w+"),
    ("QK_BFF", r"_Z23kernel_build_first_flat\w+"),
    ("QK_DIG", r"_Z13kernel_digest\w+"),
    ("QK_GT",  r"_Z19kernel_build_gtable\w+"),
    ("QK_HEAL", r"_Z19kernel_gt_heal_scan\w+"),
]
names = []
for kid, pat in want:
    hits = sorted(set(re.findall(pat, syms)))
    if len(hits) != 1:
        sys.exit(f"build_carrier: {kid} matched {hits}")
    names.append(hits[0])
# Build fingerprint plus every global the host uploads with QSB_TO_SYMBOL (tree.cu and
# window_schedule_shared.cuh). Edit this list if an upload is added or removed.
for g in ("qsb_carrier_knobs", "QSB_CONST_SCHEDULE", "QSB_U2R", "QSB_U2R_ISO", "QSB_ISO_INVU",
          "QSB_ISO_XNEG", "QSB_U2R_C", "QSB_PUSH_WORDS", "BINOM_C", "WIN3", "QSB_WINDOW_FIRST",
          "QSB_WINDOW_SECOND", "QSB_WINDOW_CLASS", "QSB_FIRST_CLASS", "QSB_LANE_CLASS",
          "QSB_FIRST_UNIQUE", "QSB_FIRST_COUNT"):
    if not re.search(r"\b%s\b" % g, syms):
        sys.exit(f"build_carrier: global {g} missing from image")
# The hint must be present in the digest kernel (the only table reader on the search path).
sass = open(W + "/sass.txt").read()
fn = re.split(r"\n\s*Function : ", sass)
dig = [b for b in fn if b.startswith(names[3])]
if not dig or "LTC64B" not in dig[0]:
    sys.exit("build_carrier: digest kernel has no LTC64B load")
n_hint = dig[0].count("LTC64B")
img = open(W + "/c.cubin", "rb").read()
b64 = base64.b64encode(img).decode()
lines = [b64[i:i + 120] for i in range(0, len(b64), 120)]
sha = hashlib.sha256(img).hexdigest()
src = hashlib.sha256()
for p in sorted(glob.glob("*.cu") + glob.glob("*.cuh") + glob.glob("*.h") +
                glob.glob("tests/gpu_epochs/*.cuh") + glob.glob("tests/gpu_epochs/*.h") +
                ["tests/gpu_epochs/tree.cu"]):
    if p == "qsb_carrier_sm89.h":
        continue
    src.update(p.encode() + b"\0" + open(p, "rb").read())
tool = open(W + "/nvcc.txt").read().strip()
with open("qsb_carrier_sm89.h", "w") as f:
    f.write("/* GENERATED by build_carrier.sh -- do not edit. Native sm_89 image of subset.cu\n")
    f.write(f" * built with -DQSB_CARRIER_BUILD=1 -DQSB_ZEROS_N={zeros} -arch=sm_89 ({tool}).\n")
    f.write(f" * cubin sha256 {sha}; {len(img)} bytes; digest kernel LTC64B loads: {n_hint}.\n")
    f.write(f" * source sha256 {src.hexdigest()} (every .cu/.cuh/.h of the build but this file). */\n")
    f.write("#pragma once\n#include <stddef.h>\n")
    f.write(f"static const size_t qsb_carrier_cubin_bytes = {len(img)};\n")
    f.write(f'static const char qsb_carrier_cubin_sha256[] = "{sha}";\n')
    f.write("static const char *const qsb_carrier_kernel_names[] = {\n")
    for kid, n in zip([k for k, _ in want], names):
        f.write(f'    "{n}", /* {kid} */\n')
    f.write("};\n")
    f.write(f"static const unsigned qsb_carrier_b64_lines = {len(lines)};\n")
    f.write("static const char *const qsb_carrier_b64[] = {\n")
    for l in lines:
        f.write(f'"{l}",\n')
    f.write("};\n")
print(f"qsb_carrier_sm89.h: {len(img)} B cubin, sha256 {sha[:16]}, {len(lines)} lines, "
      f"LTC64B loads in digest: {n_hint}, {tool}")
PY
grep -A2 "Compiling entry function '_Z13kernel_digest" "$W/ptxas.log" | tail -n 2 || true
echo "build logs: $W"
